### PR TITLE
Cache `run_sync_soon` in runtime.rs

### PR DESCRIPTION
**Pull request by TimeEngineer**
# What has changed ?

- [ ] Does this PR affect the User ?

### CODE REVIEW

**Review by FirelightFlagboy — COMMENTED** [review]
The change are ok, but how do we measure the performance increase/decrease ?

**Comment by TimeEngineer** [comment]
It seems there is no difference as I expected

**Comment by FirelightFlagboy** [comment]
How did you measure ?

**Comment by TimeEngineer** [comment]
I check test time, because binding has downgraded

**Pull request closed without merging**
