### PR TITLE
move pip installation for parsec on documentation

### LINKED ISSUE #4381: Remove part of the doc referencing client install using pip
Only backend should be installed by pip.

### PR DESCRIPTION
**Pull request by steevenakintilo**
# What has changed ?
Closes #4381

### CODE REVIEW

**Review by FirelightFlagboy — APPROVED** [review]
Should we add a news fragment for this ? @touilleMan

**Review by FirelightFlagboy — CHANGES_REQUESTED** [review]
The README also need to be updated: https://github.com/Scille/parsec-cloud/issues/4381#issuecomment-1499060719

You need to link the PR to the issue

**Comment by steevenakintilo** [comment]
> The README also need to be updated: [#4381 (comment)](https://github.com/Scille/parsec-cloud/issues/4381#issuecomment-1499060719)
> 
> You need to link the PR to the issue

I have also remove pip from the README

**Comment by FirelightFlagboy** [comment]
Nice, you only need to link the issue now :)

**Comment by steevenakintilo** [comment]
> Nice, you only need to link the issue now smile

How can I do that?

**Comment by FirelightFlagboy** [comment]
> How can I do that?

They're multiple way to do that, one is to add `Close #<ISSUE_ID>` to the description.

For the others go to <https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue>

**Comment by steevenakintilo** [comment]
> > How can I do that?
> 
> They're multiple way to do that, one is to add `Closes #<ISSUE_ID>` to the description.
> 
> For the others go to https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

thanks you

**Comment by steevenakintilo** [comment]
> > How can I do that?
> 
> They're multiple way to do that, one is to add `Closes #<ISSUE_ID>` to the description.
> 
> For the others go to https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

Just changed description name did i do it right?

**Comment by FirelightFlagboy** [comment]
Nope :stuck_out_tongue: 

You have modified the title of the PR not the body

**Comment by steevenakintilo** [comment]
> Nope stuck_out_tongue
> 
> You have modified the title of the PR not the body

Oh I'm dumb I think it's now better

**Comment by steevenakintilo** [comment]
r

> Better but you have used the id of this PR itself, that wont work.
> 
> Use #4381

Thanks I think I did it right now

**Review by FirelightFlagboy — APPROVED** [review]

**Pull request merged**
