### PR TITLE
Format platform storage correctly

### PR DESCRIPTION
**Pull request by TimeEngineer**
## Describe your changes

Format correctly the platform storage.

## Checklist

Before you submit this pull request, please make sure to:

- [x] Keep changes in the pull request as small as possible
   
- [x] Ensure the commit history is sanitized
   
- [x] Give a meaningful title to your PR
- [x] Describe your changes
   
- [x] Link any related issue in the description
   
- [x] Link any dependent pull request in the description

If this PR adds a new feature or fixes a bug:

- [ ] I have added or updated relevant tests

If this PR modifies installation or updates packages:

- [ ] I have checked that installation works on all platforms (Windows, Linux, Mac ...)
    

- [ ] I have updated related documentations (installation commands, fix to specific problems ...)

If this PR is related to GUI:

- [ ] I have checked that GUIs affected by my changes are working properly.

If this PR affects the user:

- [ ] I have created a news fragment
   
- [ ] I have updated the user documentation

### CODE REVIEW

**Comment by FirelightFlagboy** [comment]
> Format platform storage correctly

What did you mean by that, `rustfmt` didn't format this part ?

**Comment by TimeEngineer** [comment]
> What did you mean by that, `rustfmt` didn't format this part ?
It formats, but it seems correct for it

**Comment by FirelightFlagboy** [comment]
Maybe we should raise an issue for `rustfmt` ?

**Comment by TimeEngineer** [comment]
Is it an issue ?

**Comment by FirelightFlagboy** [comment]
For me yes, because `rustfmt` did not format those code blocks. 
The goal of using a formater is to remove the code formatting constraint to the developer.

**Review by FirelightFlagboy — APPROVED** [review]
Open an issue for `rustfmt` if you can.

**Comment by TimeEngineer** [comment]
https://github.com/rust-lang/rustfmt/issues/3863
https://github.com/rust-lang/rustfmt/issues/5850

**Pull request merged**
