### PR TITLE
Is ready overengineering ?

### PR DESCRIPTION
**Pull request by TimeEngineer**
# What has changed ?

- [ ] Does this PR affect the User ?

### CODE REVIEW

**Review by FirelightFlagboy — COMMENTED** [review]
Did you perform a benchmark with the 2 implementation ? (Don't trust the CI timing)

**Comment by TimeEngineer** [comment]
It's not about performance, it's about overengineering, do we want to have more complexity in our binding for some ms ?

**Comment by FirelightFlagboy** [comment]
I understand you point but if it slow down too much the code I don't think it's good to merge it

**Comment by TimeEngineer** [comment]
That's why this PR is opened, if it's slow down a lot, this PR will be closed ^^

**Comment by FirelightFlagboy** [comment]
# The process to do a benchmark

1. Download <https://github.com/Scille/parsec-cloud/archive/refs/tags/v2.15.0.zip>.
2. Extract the zip file.
    > You can also build `parsec-2.15` to generate more files (I think of the `target` folder)
4. On the main branch and on your branch
    1. Compile parsec in release mode.
    2. Run `tests/script/run_testenv.sh`
    3. Follow its indication to connect as `alice` with the CLI command
    5. On another shell `time cp -R <path where you extracted parsec-2.15> ~/Parsec/alice/parsec-2.15`
    6. Save the taken time.
    7. On the shell that run `testenv` execute the function `cleanup` to stop it.
4. Compare both time

**Comment by TimeEngineer** [comment]
Data size: `20.1 MB`
CPU: `AMD Ryzen 7 3800X 8-Core Processor`
CPU frequency: `3899.916 MHz`
Cache size : `512 KB`

master:
```
real    0m42,383s
user    0m0,052s
sys     0m0,147s
```
branch:
```
real    0m54,137s
user    0m0,029s
sys     0m0,167s
```

**Pull request closed without merging**
