### PR TITLE
Fix `change_authentification`

### PR DESCRIPTION
**Pull request by TimeEngineer**

### CODE REVIEW

**Review by FirelightFlagboy — COMMENTED** [review]
Can you add a test ?

**Review by FirelightFlagboy — COMMENTED** [review]
I would prefer that the param `with_template` to be renamed to `load_from_testbed_template`

**Comment by TimeEngineer** [comment]
> I would prefer that the param `with_template` to be renamed to `load_from_testbed_template`

It's not necessary coming from `testbed_template`: It's search first from the `cache`, then if it doesn't find, it will retrieve from the `testbed template`

**Comment by FirelightFlagboy** [comment]
I would like that the parameter have at least the indication that it's only used by the testbed

**Comment by TimeEngineer** [comment]
> I would like that the parameter have at least the indication that it's only used by the testbed

I changed for `with_testbed_template`

**Review by FirelightFlagboy — APPROVED** [review]

**Pull request merged**
