### PR TITLE
Upgrade to quart 0.18.0

### PR DESCRIPTION
**Pull request by touilleMan**
requires https://github.com/pgjones/quart-trio/issues/3 to be fixed

### CODE REVIEW

**Comment by FirelightFlagboy** [comment]
@touilleMan the issue pgjones/quart-trio#3 is now merged

**Comment by touilleMan** [comment]
must wait for https://github.com/pallets/quart/issues/174 to be fixed

**Comment by FirelightFlagboy** [comment]
@touilleMan the issue 

- pallets/quart#174

is fixed 🎉

**Comment by touilleMan** [comment]
@FirelightFlagboy we must wait for quart 0.18.1 now ;-)

**Review by vxgmichel — APPROVED** [review]

**Review by FirelightFlagboy — APPROVED** [review]

**Pull request merged**
