### PR TITLE
Reenable manifest update lock guard release check

### PR DESCRIPTION
**Pull request by touilleMan**
close https://github.com/Scille/parsec-cloud/issues/8579

### CODE REVIEW

**Review by FirelightFlagboy — COMMENTED** [review]
Does this PR fix an issue ? (that is not linked)

For me, this PR lack a test that would have failed without the patch

**Comment by touilleMan** [comment]
> Does this PR fix an issue ? (that is not linked)

Nop, I've created #8579
(I don't think a newsfragment is needed for this PR though, given it fixes something that is most likely invisible for the end user)

> For me, this PR lack a test that would have failed without the patch

That's the trick: without this patch we can get guard not released but right at the moment we stop the WorkspaceOps, so no deadlock should occur since everything is expected to go down.

However the key point here is we introduce deadlocking code without realizing it which is very bad !

Hence the re-enabling of the lock-released-before-drop check to protect us against this kind of errors (that can be much more serious that what we got here !).

**Comment by FirelightFlagboy** [comment]
It's not possible to show that `ManifestUpdateLockGuard` was not released prior to being dropped before the patch ?

:thinking: That would be possible to `log::error` was replaced by a panic, but ... that may not be something we want

**Comment by touilleMan** [comment]
> That would be possible to log::error was replaced by a panic, but ... that may not be something we want

That was precisely what the commented code was doing, see the comment about why this was commented in the first place

**Review by FirelightFlagboy — APPROVED** [review]

**Pull request merged**
