### PR TITLE
Add absolute path in mountpoint error events

### LINKED ISSUE #1775: Bad handling of CoreEvent.MOUNTPOINT_UNHANDLED_ERROR event
Sentry Issue: [PARSEC-QX0](https://sentry.io/organizations/scille/issues/2482951314/?referrer=github_integration)

```
BackendConnectionRefused: Error while fetching organization config: {'reason': 'Unknown command', 'status': 'unknown_command'}
  File "parsec/core/fs/remote_loader.py", line 77, in translate_backend_cmds_errors
    yield
  File "parsec/core/fs/remote_loader.py", line 342, in load_block
    rep = await self.backend_cmds.block_read(access.id)
  File "parsec/core/backend_connection/expose_cmds.py", line 37, in wrapper
    async with self.acquire_transport(allow_not_available=True) as transport:
  File "async_generator/_util.py", line 34, in __aenter__
    return await self._agen.asend(None)
  File "parsec/core/backend_connection/authenticated.py", line 346, in _acquire_transport
    raise copy_exception(self.status_exc)

FSError: Error while fetching organization config: {'reason': 'Unknown command', 'status': 'unknown_command'}
(10 additional frame(s) were not displayed)
...
  File "parsec/core/fs/workspacefs/file_transactions.py", line 265, in fd_read
    await self.remote_loader.load_blocks(missing)
  File "parsec/core/fs/remote_loader.py", line 329, in load_blocks
    await self.load_block(access)
  File "parsec/core/fs/remote_loader.py", line 342, in load_block
    rep = await self.backend_cmds.block_read(access.id)
  File "contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "parsec/core/fs/remote_loader.py", line 81, in translate_backend_cmds_errors
    raise FSError(str(exc)) from exc

AssertionError: 
  File "parsec/event_bus.py", line 89, in send
    cb(event, **kwargs)
  File "parsec/core/gui/central_widget.py", line 230, in handle_event
    assert isinstance(kwargs["path"], str)

{'callback': <bound method CentralWidget.handle_event of <parsec.core.gui.central_widget.CentralWidget object at 0x7f6be0043048>>, 'event_type': <CoreEvent.MOUNTPOINT_UNHANDLED_ERROR: 'mountpoint.unhandled_error'>, 'exc': FSError("Error while fetching organization config: {'reason': 'Unknown command', 'status': 'unknown_command'}",), 'operation': 'read', 'path': FsPath('/xxx.pdf'), 'event': 'Unhandled exception in event bus callback', 'l...
```

### PR DESCRIPTION
**Pull request by touilleMan**
fix #1775

### CODE REVIEW

**Review by vxgmichel — APPROVED** [review]
LGTM, it doesn't really fix #1775 tho does it?

Also I wonder if want to emit more information like the workspace id and local path.

**Comment by touilleMan** [comment]
> LGTM, it doesn't really fix #1775 tho does it?

#1775 has three exceptions in one:
- `unknown_command` status returned by the backend which is unexpected by the client (fixed by #1779)
- `FSError` is unexpected in fuse_operations, given the exception is originally a `BackendConnectionRefused` it should have been reraised as `FSRemoteOperationError`, this hasn't been addressed
- ` assert isinstance(kwargs["path"], str)` cause an `AssertionError` because the `CoreEvent.MOUNTPOINT_UNHANDLED_ERROR` event is emitted without a required `path` field, the current PR fix this issue \o/

> Also I wonder if want to emit more information like the workspace id and local path.

`abspath` correspond to the path of the file on the disk, another possibility would be to provide the mountpoint path (i.e. `/home/foo/Parsec/my_workspace` or `P://`) and the file path within the workspace (i.e. `/foo/bar.txt`). This might be better to understand where in the path the mountpoint kicks in.

`worspace_id` might be a good idea (especially given it's not a sensitive information so why not add it ^^)

**Review by vxgmichel — APPROVED** [review]
LGTM :+1:

**Review by Ironicbay — APPROVED** [review]
LGTM!

**Review by vxgmichel — APPROVED** [review]
:+1:

**Pull request merged**
