### PR TITLE
Fix snapcraft parsec scheme typo

### PR DESCRIPTION
**Pull request by FirelightFlagboy**

### CODE REVIEW

**Review by mmmarcos — APPROVED** [review]

**Review by Max-7 — CHANGES_REQUESTED** [review]
It should be `parsec3://` I think xD

**Comment by FirelightFlagboy** [comment]
That's not how `mime-type` is configured

**Comment by Max-7** [comment]
Invitation links generated by the app starts with `parsec3://` (parsec3://saas-demo-v3-fireraptor.parsec.cloud/MaxTest2703?action=claim_user&token=408932df11d84cd8ab6ba5fc953fdc74 for example).

It's also what the app is expecting (https://github.com/Scille/parsec-cloud/blob/c3f02e54e92582dacd7f0edf5f717b77a3c44e48/client/electron/src/setup.ts#L294)

**Comment by FirelightFlagboy** [comment]
My comment still stand, you don't specify `://` when configuring the scheme handler in mime.

**Comment by FirelightFlagboy** [comment]
Oh, right :sweat_smile:

**Review by Max-7 — APPROVED** [review]

**Pull request merged**
