### PR TITLE
Improve logged core methods exceptions

### PR DESCRIPTION
**Pull request by touilleMan**

### CODE REVIEW

**Review by vxgmichel — APPROVED** [review]
So what's the criteria to tell the backend exceptions apart from the invite exceptions?

LGTM otherwise!

**Comment by vxgmichel** [comment]
[Also](https://dev.azure.com/Scille/parsec/_build/results?buildId=5623&view=logs&j=428b1e07-02b6-507b-4a77-51bcad7c9856&t=a27b1a93-6833-5431-656a-8bb4e1bbe530&l=20):
> ImportError: cannot import name 'BackendInvitationOnExistingMember'

**Comment by touilleMan** [comment]
> So what's the criteria to tell the backend exceptions apart from the invite exceptions?

The idea is to use `BackendConnectionError` for the `LoggedCore`'s additonal methods (given those methods mostly wrap command sending to the backend). From there, it's a small hack to add more specific exceptions types to inheriting from `BackendConnectionError`.

On the other hand, the `InviteError` exceptions are raised only by the claimer/greeter ctx classes (so `UserClaimInitialCtx`, `UserClaimInProgress2Ctx` etc.).

So in the end it would be better to have an unified exception class, but in the meantime this is an attempt to have something clean enough ;-)

**Review by vxgmichel — APPROVED** [review]

**Comment by vxgmichel** [comment]
https://dev.azure.com/Scille/parsec/_build/results?buildId=5664&view=logs&j=5ba45810-c0e9-5996-abe7-b2cb0c9b6baa&t=b18150ab-3a6d-5272-0b08-a0dc06a2acd4&l=264

**Pull request merged**
