### PR TITLE
fix: remove @electron/rebuild package from client/electron/package.json

### PR DESCRIPTION
**Pull request by luansmartr**
## Describe your changes
This pull request is about remove @electron/rebuild package from client/electron/package.json since it cause error 

`@electron/rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies`

## Checklist

Before you submit this pull request, please make sure to:

- [x] Keep changes in the pull request as small as possible
   
- [x] Ensure the commit history is sanitized
   
- [x] Give a meaningful title to your PR
- [x] Describe your changes
   
- [x] Link any related issue in the description
   
- [x] Link any dependent pull request in the description

If this PR adds a new feature or fixes a bug:

- [x] I have added or updated relevant tests

If this PR modifies installation or updates packages:

- [x] I have checked that installation works on all platforms (Windows, Linux, Mac ...)
    

- [x] I have updated related documentations (installation commands, fix to specific problems ...)

If this PR is related to GUI:

- [x] I have checked that GUIs affected by my changes are working properly.

If this PR affects the user:

- [x] I have created a news fragment
   
- [x] I have updated the user documentation

### CODE REVIEW

**Comment by FirelightFlagboy** [comment]
I've tested your change myself, It work.

Now you just need to wait for someone from @Scille/js-code-owners to approve that PR

**Comment by luansmartr** [comment]
> I've tested your change myself, It work.
> 
> Now you just need to wait for someone from @Scille/js-code-owners to approve that PR

Thank sir

**Review by FirelightFlagboy — COMMENTED** [review]
@luansmartr It appears that the file `package-lock.json` was not updated, could you perform an `npm install` to update it ?

**Comment by luansmartr** [comment]
@FirelightFlagboy do you prefer `yarn.lock` be also updated?

**Comment by FirelightFlagboy** [comment]
We don't have a `yarn.lock` since we use `npm` (do we have a `yarn.lock` in the repository ?)

**Comment by luansmartr** [comment]
> We don't have a `yarn.lock` since we use `npm` (do we have a `yarn.lock` in the repository ?)

I use yarn for install packages, my bad. I will update package-lock.json

**Review by FirelightFlagboy — APPROVED** [review]
LGTM, waiting an approval from @Scille/js-code-owners

**Review by NicoTuxx — APPROVED** [review]

**Pull request merged**
