### PR TITLE
Acknowledge release 3.0.0

### PR DESCRIPTION
**Pull request by vxgmichel**

### CODE REVIEW

**Review by mmmarcos — APPROVED** [review]
LGTM

**Review by FirelightFlagboy — APPROVED** [review]

**Review by FirelightFlagboy — CHANGES_REQUESTED** [review]
Do not merge

**Comment by FirelightFlagboy** [comment]
The PR was not creating from the script `python misc/releaser acknowledge 3.0.0`.
This is problematic since the head ref is `release/3.0`, if we merge it it will result in the said branch to be closed. 
We do not want that as we want the branches `releases/*` to be perennial.

I'll close since PR and create a new one

**Comment by FirelightFlagboy** [comment]
Superseded by #8440

**Pull request closed without merging**
